### ISSUE TITLE
multiple source files in gcc parameter list  not handled properly

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#129]
For example in the following case the ctu-analyze phase will fail.

CodeChecker log -b "gcc -c ./caller.c ./lib.c" -o build.json
rm -rf ./.ctu
ctu-build.py -j1 -v -b build.json -p .ctu
rm -rf ./.ctu-out
ctu-analyze.py -j1 -o ./.ctu-out -v -p .ctu -b ./build.json

**Comment by gerazo** [comment]
It turns out this is a misfeature of analyze-cc. The reason is that intercept-build never creates a buildlog.json which contains multiple sources per command. As the compilation db has a format where there is exactly one file for a command, intercept-build intelligently creates a command line where only that file is left in the compiled parameters. This way, analyze-cc should not handle this normally. Should we emulate the same behaviour?
