### ISSUE TITLE
create reviews.llvm.org patch for '!CheckName.empty()'

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#303]
https://github.com/Ericsson/clang/pull/302

**Comment by balazske** [comment]
The problem is fixed in the clang repository already:
https://reviews.llvm.org/rC323052
This is somewhat other way of solution as our #302, probably it should be replaced with this because they seem to know more about why this problem happens (the original assertion does not occur with this 
fix)? There is a test for it too (is this needed in our branch?).

**Comment by Xazax-hun** [comment]
Merged.
