### ISSUE TITLE
Missing FunctionTemplateDecl (warning)

### ISSUE THREAD

**Issue by martong** [Ericsson/clang#344]
```
TEST_F(Fixture, MissingFunctionTemplateDecl) {
  Decl *FromTU = getTuDecl(
      R"(
namespace std {
template <typename> struct __and_;
template <typename> struct is_default_constructible;
template <typename> struct __is_implicitly_default_constructible;
template <bool> struct enable_if;
struct pair {
  template <typename, typename _U2,
            typename enable_if<__and_<
                __is_implicitly_default_constructible<_U2>>::value>::type>
  pair();
  template <
      typename, typename _U2,
      typename enable_if<__and_<is_default_constructible<_U2>>::value>::type>
  pair();
};
class string;
}
namespace google {
namespace protobuf {
using std::string;
namespace internal {
void IsStructurallyValidUTF8(const char *, int) {}
}
}
}
            )",
      Lang_CXX11, "input1.cc");
  FunctionDecl *FromD = FirstDeclMatcher<FunctionDecl>().match(
      FromTU, functionDecl(hasName("IsStructurallyValidUTF8")));
  Import(FromD, Lang_CXX11);
}
```

**Comment by bruntib** [comment]
This is a clearer minimal example for the issue:
```.cpp
template <typename>
struct S1;

template <typename>
struct S2;

template <bool>
struct enable_if;

struct S
{
  template <typename T, typename enable_if<S1<T>::value>::type>
  void f();

  template <typename T, typename enable_if<S2<T>::value>::type>
  void f();
};
```

The problem is that according to Clang the type of `S1<T>::value` and `S2<T>::value` expressions are both "builtin". The string representation of this type is also `<builtin type>` or something similar.

Adding the following code fragment to the end of `IsStructurallyEquivalent(StructuralEquivalenceContext&, QualType, QualType)` function in the file `ASTStructuralEquivalence.cpp` solves the issue:
```.cpp
if (T1.getAsString() != T2.getAsString())
  return false;
```
I'll continue finding a nicer solution, such as getting the qualifier of `S1<T>::value` if possible and checking its equivalence.

Unfortunately this fix doesn't help in CTU errors which also produce this warning.

**Comment by dkrupp** [comment]
with final solution please wait for this patch:
https://github.com/Ericsson/clang/issues/406

**Comment by Xazax-hun** [comment]
Is this even valid to query the type of `S2<T>::value` and `S1<T>::value`? Note that the type of `value` depends on the template argument that is passed to this template. So we cannot know the type. In these cases it is an error to compare the types we should do something else.

**Comment by bruntib** [comment]
Sorry, I meant that the qualifier should rather be checked for equivalence: `S1<T>` vs. `S2<T>`. However it is a good question what happens if the actual types of `S1<T>::value` and `S2<T>::value` are equal/equivalent. But in that case the ODR is violated.

**Comment by Xazax-hun** [comment]
`S1<T>` still does not have a type. It will only have a type in a template instantiation but not in the template. So not getting the correct type is expected and moreover I would expect querying the type to be a crash or assertion failure.

**Comment by Xazax-hun** [comment]
Having the same type for `S1<T>::value` and `S2<T>::value` is possible without any ODR violations, both can be an `int` for instance.

**Comment by bruntib** [comment]
> `S1<T>` still does not have a type.

`S1<T>` is a type itself which is not equivalent with `S2<T>`. Proper detection of this fact would be the nice solution instead of this fixing proposal (using string representation). Or who knows whether it is a structural inequality if only the name differs. Anyway, in this case this is the only point which distinguishes the two function templates which otherwise would violate ODR (if both `S1<T>::value` and `S2<T>::value` are `int`s for example).

**Comment by Xazax-hun** [comment]
I am not sure whether `S1<T>` is a type. You cannot have a variable of type `S1<T>`. You could have one of type `S1<int>`.

**Comment by bruntib** [comment]
Dependent type. You know what I mean... :stuck_out_tongue_winking_eye:

**Comment by Xazax-hun** [comment]
I see. If we follow the logic of stuctural equivalence, the equality check for `S1<T>` and `S2<T>` should recurse to equivalence check for S1 and S2, and equivalence check for T and T. This way we do not need to rely on string equivalence.

**Comment by bruntib** [comment]
And this is what I intended to say in the beginning. Sorry, if not succeeded :)

**Comment by Xazax-hun** [comment]
But in this case, I do not see why do we need to wait for #406 with the fix. As you can see in the discussion of #406 if the source range comparison fails we might need to fall back to structural equivalence. So we need to fix the structural equivalence regardless of the state of #406.

**Comment by martong** [comment]
In the latest ctu-clang7 commit (6e42c1eaaf1759852626e152a2505b64f9de9606) we cannot reproduce this issue with the given unittest.

**Comment by martong** [comment]
The original `import` test indeed does not fail but a structural eq test one the code provided by @bruntib is still an issue:
```
template <typename>
struct S1;

template <typename>
struct S2;

template <bool>
struct enable_if;

struct S
{
  template <typename T, typename enable_if<S1<T>::value>::type>
  void f();

  template <typename T, typename enable_if<S2<T>::value>::type>
  void f();
};
```
Above, the two consecutive `f` FunctionTemplateDecl are considered structurally equivalent, but they should not be.

**Comment by martong** [comment]
#600 Fixes this.
