### ISSUE TITLE
try to replace isstructurallyEquivalent by isSameBySourceLoc()

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#406]
Structural equivalence in ast importer is not enough in some cases, because it does not take names into consideration and regards two diffent declaration equivalent in cases when they are not.
See https://github.com/Ericsson/clang/issues/344

Try to use an equivalence check which works by source location instead of structural equivalence.

**Comment by Xazax-hun** [comment]
Note that source location is not always a good choice. There can be multiple declarations of the same function for instance, and each declaration will have separate source location. We have to be careful when to compare source ranges/locations (and their content) and when do we use structural equivalence. So we cannot replace structure equivalence.

**Comment by Xazax-hun** [comment]
I think the error in #344 is the result of not doing the right thing, i.e. we are trying check the equivalence of types when we do not have any types in the first place. So the error is not inherent to structural equivalence checking, just a bug in the implementation.

**Comment by balazske** [comment]
If we find the same declaration with the new "source location check" it is sure that it already exists. If not we should do a structural equivalence search like it is done now, to find a "previous decl". This "previous decl" is always used as previous decl, not to merge with the currently imported Decl.

**Comment by martong** [comment]
related: #384

**Comment by martong** [comment]
We had a discussion about this with @bruntib and with Gsd. Looks like this improvement is not feasible because of the following reasons.

Consider these files:
```
// A.h
struct A {
  char x[SIZE];
};

// Tu0.cpp
#define SIZE 1
#include "A.h"
void f0(A a) {}

// Tu1.cpp
#define SIZE 2
#include "A.h"
void f1(A a) {}
```

Here, `Tu0/A` and `Tu1/A` are not structurally equivalent but they have the very same source location in `A.h`. More specifically, their spelling location is the same, the only difference is in the definition of `SIZE`. We could link `Tu0.o` with `Tu1.o` because the executable format does not store any type information. Consequently, on the AST level we must keep both versions of `A`; in a way that `f0` and `f1` are referring to their own different version of `A`.

Alternatives:

* Checking the USR besides the source location
The USR of `Tu0/A` and `Tu1/A` is equal, also the array fields has the same USR. This will not work.

* Checking the Macro state besides the source location
We still could somehow check the macro state together with the source locations, but that seems quite complicated too (does the included files or the order of included files changes the macro state?).

* Use the AST hashing algorithm which is used for modules instead of structural eq.
This might worth a try, because they try to solve something similar there. Last time I checked it was not complete and they were not checking that much as we do check in structural eq, so definitely we would need to contribute to the hashing algorithm ... which has again pros and cons.
