### ISSUE TITLE
Revisit `ToDecl->hasBody()` assert with respect to ODR violations

### ISSUE THREAD

**Issue by martong** [Ericsson/clang#448]
We should assert only if there were no ODR violations.
We will emit a warning during ODR violations, and increase a clang statistics variable, but we will not assert in CTU.cpp if there were ODR violations.

Also, unsupported node warnings should be removed, instead we should fall back to assertions similarly as it is done in upstream.

**Comment by martong** [comment]
related #442

**Comment by balazske** [comment]
Upstream has no assert at unsupported node, only warning.
The "unsupported node" can not be fully removed, there may be some unsupported constructs that are not importable, the only one case is now the "struct definition in function parameter". In general case there will be assert at import of unknown node, for known cases that can not be imported the specific import function must be implemented to set the "unsupported construct" flag.

**Comment by martong** [comment]
Ok, sounds good to me.

**Comment by balazske** [comment]
Related pull request: #450

**Comment by balazske** [comment]
ODR detection is not perfect in `ASTImporter`, there are hidden problems related to `HandleNameConflict` and detection of "conflicting" names. It could be corrected that unit tests do work, but still not every case is correct (no problem report at specific ODR error cases?).

**Comment by balazske** [comment]
Handling of import at `CrossTranslationUnitContext` needs to be changed. If import of some function does fail because ODR (or other) problem, it can result in that something is not imported. At import of a next function this can cause that the function body is not imported because the previous problems (but in this last case no ODR problem is detected). The "hasBody" assertion can be removed, `importDefinition` can return `nullptr` in this case. Anyway, at every case when any `Import` call returns `nullptr` it may leave an inconsistent AST (the new node is probably created and partially initialized).

**Comment by martong** [comment]
> If import of some function does fail because ODR (or other) problem, it can result in that something is not imported. At import of a next function this can cause that the function body is not imported because the previous problems (but in this last case no ODR problem is detected).

Do we have the same object of the `ASTImporter` class during the import of the two subsequent functions?
I think yes, but then we should know that there had been an error previously, don't we?

**Comment by balazske** [comment]
Related: #457

**Comment by dkrupp** [comment]
Let's wait with the commit to CTU-clang for the open source patch to get in 
https://reviews.llvm.org/D51633
