### ISSUE TITLE
Simplify ASTImporting in LLDB

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#638]
remove getOriginDecl(..) from lldb

**Comment by martong** [comment]
We can't remove `getOriginalDecl` yet. Because while `ImportedFromDecls` does not have an entry for the given "to" Decl, `getOriginalDecl` still provides an entry.

`./bin/lldb-dotest -p TestVectorOfEnums -t` of https://reviews.llvm.org/D59847 fails when we use onlye the `ImportedFromDecls`.

We may try to eliminate `getOriginalDecl` again, once we have the `ImportedFromDecls` in `ASTImporterSharedState` and once the sharedstate is introduced in LLDB too.
